import React, { useState, useEffect, useMemo, useRef, useCallback } from "react";import { supabase } from './supabase'

const SURAHS = [
  {n:1,name:"Al-Fatiha",ar:"الفاتحة",v:7,juz:1,type:"Mecquoise"},
  {n:2,name:"Al-Baqara",ar:"البقرة",v:286,juz:1,type:"Médinoise"},
  {n:3,name:"Al-Imran",ar:"آل عمران",v:200,juz:3,type:"Médinoise"},
  {n:4,name:"An-Nisa",ar:"النساء",v:176,juz:4,type:"Médinoise"},
  {n:5,name:"Al-Maida",ar:"المائدة",v:120,juz:6,type:"Médinoise"},
  {n:6,name:"Al-Anam",ar:"الأنعام",v:165,juz:7,type:"Mecquoise"},
  {n:7,name:"Al-Araf",ar:"الأعراف",v:206,juz:8,type:"Mecquoise"},
  {n:8,name:"Al-Anfal",ar:"الأنفال",v:75,juz:9,type:"Médinoise"},
  {n:9,name:"At-Tawba",ar:"التوبة",v:129,juz:10,type:"Médinoise"},
  {n:10,name:"Yunus",ar:"يونس",v:109,juz:11,type:"Mecquoise"},
  {n:11,name:"Hud",ar:"هود",v:123,juz:11,type:"Mecquoise"},
  {n:12,name:"Yusuf",ar:"يوسف",v:111,juz:12,type:"Mecquoise"},
  {n:13,name:"Ar-Ra\u2019d",ar:"الرعد",v:43,juz:13,type:"Médinoise"},
  {n:14,name:"Ibrahim",ar:"إبراهيم",v:52,juz:13,type:"Mecquoise"},
  {n:15,name:"Al-Hijr",ar:"الحجر",v:99,juz:14,type:"Mecquoise"},
  {n:16,name:"An-Nahl",ar:"النحل",v:128,juz:14,type:"Mecquoise"},
  {n:17,name:"Al-Isra",ar:"الإسراء",v:111,juz:15,type:"Mecquoise"},
  {n:18,name:"Al-Kahf",ar:"الكهف",v:110,juz:15,type:"Mecquoise"},
  {n:19,name:"Maryam",ar:"مريم",v:98,juz:16,type:"Mecquoise"},
  {n:20,name:"Ta-Ha",ar:"طه",v:135,juz:16,type:"Mecquoise"},
  {n:21,name:"Al-Anbiya",ar:"الأنبياء",v:112,juz:17,type:"Mecquoise"},
  {n:22,name:"Al-Hajj",ar:"الحج",v:78,juz:17,type:"Médinoise"},
  {n:23,name:"Al-Muminun",ar:"المؤمنون",v:118,juz:18,type:"Mecquoise"},
  {n:24,name:"An-Nur",ar:"النور",v:64,juz:18,type:"Médinoise"},
  {n:25,name:"Al-Furqan",ar:"الفرقان",v:77,juz:18,type:"Mecquoise"},
  {n:26,name:"Ash-Shuara",ar:"الشعراء",v:227,juz:19,type:"Mecquoise"},
  {n:27,name:"An-Naml",ar:"النمل",v:93,juz:19,type:"Mecquoise"},
